name: Build and deploy docs

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-upload:
    name: Build docs and upload GitHub Pages artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -U
          -e .
          -r requirements.txt
          -r requirements-dev.txt

      - name: Generate docs
        run: |
          pdoc
          --docformat google
          --edit-url screenshot_ocr=https://github.com/cofiem/screenshot-ocr/blob/main/src/screenshot_ocr/
          --search
          --show-source
          --output-directory docs
          ./src/screenshot_ocr

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy-pages:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-upload
    if: github.repository_owner == 'cofiem' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy docs to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
